FROM python:3.11-slim

WORKDIR /app

COPY Requirements.txt .
RUN pip install --no-cache-dir -r Requirements.txt

COPY NovaTechChatBot.py .
COPY Documents/ ./Documents/

#Hugging Faces usually requires port 7860.
CMD ["uvicorn","NovaTechChatBot:api","--host","0.0.0.0","--port","7860"]